<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\FrontendMetadataApi\ViewModel\PageMetaInterface;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var Template $block
 * @var PageMetaInterface $pageMetaViewModel
 * @var SecureHtmlRenderer $secureRenderer
 */
$pageMetaViewModel = $block->getPageMetaViewModel();
?>
<?php if (!$pageMetaViewModel->isEnabled()): ?>
    <?php return; ?>
<?php endif; ?>

<?php
$scriptString = "
    require(['Magento_Customer/js/customer-data'], function (customerData) {
        var cart = customerData.get('cart');
        var count = cart().summary_count;
        cart.subscribe(function () {
            if (cart().summary_count !== count) {
                const data = {
                    'page': {
                        'cart': customerData.get('klevu_metadata_cart')
                    }
                };
                window._klvReady = window._klvReady || [];
                window._klvReady.push(function() {
                     klevu.pageMeta.update(data, 2);
                });
            }
        });
    });
    ";
?>
<?= $secureRenderer->renderTag(
    tagName: 'script',
    attributes: [
        'type' => 'text/javascript',
        'id' => 'klevu_cart_meta',
    ],
    content: $scriptString,
    textContent: false,
) ?>
