<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\FrontendMetadataApi\ViewModel\PageMetaInterface;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var Template $block
 * @var PageMetaInterface $pageMetaViewModel
 * @var SecureHtmlRenderer $secureRenderer
 */
$pageMetaViewModel = $block->getPageMetaViewModel();
?>
<?php if (!$pageMetaViewModel->isEnabled()): ?>
    <?php return; ?>
<?php endif; ?>

<?php $pageMeta = $pageMetaViewModel->getMeta(); ?>
<?php
$scriptString = "
    window.klevu_meta = {$pageMeta};
    klevu.support.hook(
        [\"pageMeta\"],
        function() {
            klevu.pageMeta.update(window.klevu_meta, 2);
        }
    );
    ";
?>
<?php
$script = "
    window._klvReady = window._klvReady || [];
    window._klvReady.push(function() {
        {$scriptString}
    });
    ";
?>
<?= $secureRenderer->renderTag(
    tagName: 'script',
    attributes: ['type' => 'text/javascript', 'id' => 'klevu_meta'],
    content: $script,
    textContent: false,
) ?>
