<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\FrontendMetadataApi\ViewModel\PageMetaInterface;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var Template $block
 * @var PageMetaInterface $pageMetaViewModel
 * @var SecureHtmlRenderer $secureRenderer
 */
$pageMetaViewModel = $block->getPageMetaViewModel();
?>
<?php if (!$pageMetaViewModel->isEnabled()): ?>
    <?php return; ?>
<?php endif; ?>

<?php
$scriptString = <<<script
    const updateMetadata = (event) => {
        // event.detail.data contains the entire sectionData
        const sectionData = event.detail.data;
        const data = {
            'page': {
                'cart': sectionData.klevu_metadata_cart ? sectionData.klevu_metadata_cart : []
            }
        };
        const pageMetaVersion = 2;
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            klevu.pageMeta.update(data, pageMetaVersion);
        });

    };
    window.addEventListener('private-content-loaded', updateMetadata, { once: false });
script;
?>
<?= $secureRenderer->renderTag(
    tagName: 'script',
    attributes: [
        'type' => 'text/javascript',
        'id' => 'klevu_cart_meta',
    ],
    content: $scriptString,
    textContent: false,
) ?>
